kind: Deployment
apiVersion: apps/v1
metadata:
  name: dpl-test3
  namespace: test3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test3
  template:
    metadata:
      labels:
        environment: dev
        release: r_09_18_v1
        tier: backend
        app: test3
    spec:
      containers:
      - name: test3
        image: gklc811/test3
        ports:
        - name: node-port
          containerPort: 5000
      nodeSelector:
        tier: backend