---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sparkmaster
  name: sparkmaster
  namespace: spark
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 8080
      targetPort: 8080
      name: ui
    - port: 7077
      targetPort: 7077
      name: tcp
  selector:
    app: sparkmaster
