kind: Deployment
apiVersion: apps/v1
metadata:
  name: dpl-test2
  namespace: test2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        environment: dev
        release: r_09_18_v1
        tier: backend
        app: test2
    spec:
      containers:
      - name: test2
        image: gklc811/test2
        ports:
        - name: node-port
          containerPort: 5000
      nodeSelector:
        tier: backend