apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: nodejs-pod
  namespace: pods-test
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: gklc811/podinfo
        ports:
        - containerPort: 5000
