kind: Service
apiVersion: v1
metadata:
  labels:
    app: podinfo
  name: podinfo
  namespace: pods-test
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: podinfo
