apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              cpu
        Tag               cpu
        Interval_Sec      10

    [INPUT]
        Name              disk
        Tag               disk
        Interval_Sec      10

    [INPUT]
        Name              mem
        Tag               mem
        Interval_Sec      10

    [INPUT]
        Name              kmsg
        Tag               kmsg
        Interval_Sec      10

    [INPUT]
        Name              netif
        Tag               netif
        Interval_Sec      10
        Interval_NSec     0
        Interface         enp0s8

    [INPUT]
        Name              tail
        Tag               containerlog
        Path              /var/log/containers/dpl*.log
        Parser            docker
        Mem_Buf_Limit     5MB


  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               *
        Kube_URL            https://kubernetes.default.svc.cluster.local:443

  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           cpu
        Host            192.168.56.61
        Port            9200
        Index           cpulog
        Type            docker

    [OUTPUT]
        Name            es
        Match           disk
        Host            192.168.56.61
        Port            9200
        Index           disklog
        Type            docker

    [OUTPUT]
        Name            es
        Match           mem
        Host            192.168.56.61
        Port            9200
        Index           memlog
        Type            docker

    [OUTPUT]
        Name            es
        Match           kmsg
        Host            192.168.56.61
        Port            9200
        Index           kmsglog
        Type            docker

    [OUTPUT]
        Name            es
        Match           netif
        Host            192.168.56.61
        Port            9200
        Index           netiflog
        Type            docker

    [OUTPUT]
        Name            es
        Match           containerlog
        Host            192.168.56.61
        Port            9200
        Index           kubecontainerlog
        Type            docker

  parsers.conf: |
    [PARSER]
        Name   apache
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache2
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache_error
        Format regex
        Regex  ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$

    [PARSER]
        Name   nginx
        Format regex
        Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        Decode_Field_As   escaped    log

    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S
