---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hdfs-namenode
  name: hdfs-namenode
  namespace: hdfs
spec:
  ports:
  - port: 8020
    name: fs
  clusterIP: None
  selector:
    app: hdfs-namenode
