apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: hdfs-namenode
  namespace: hdfs
spec:
  serviceName: "hdfs-namenode"
  replicas: 1
  template:
    metadata:
      labels:
        app: hdfs-namenode
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: hdfs-namenode
          image: registry.gokul.com:5000/gokul/hdfs-namenode
          env:
            - name: CLUSTER_NAME
              value: hdfs-k8s
          ports:
          - containerPort: 8020
            name: fs
      restartPolicy: Always
