apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: hdfs-datanode
  namespace: hdfs
spec:
  serviceName: "hdfs-datanode"
  replicas: 1
  template:
    metadata:
      labels:
        app: hdfs-datanode
    spec:
      containers:
        - name: datanode
          image: registry.gokul.com:5000/gokul/hdfs-datanode
          env:
            - name: CORE_CONF_fs_defaultFS
              value: hdfs://hdfs-namenode-0.hdfs-namenode.hdfs.svc.cluster.local:8020
          ports:
          - containerPort: 50010
            name: fs
      restartPolicy: Always
