kind: Service
apiVersion: v1
metadata:
  labels:
    app: test1
  name: svc-test1
  namespace: test1
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: test1