kind: Deployment
apiVersion: apps/v1
metadata:
  name: dpl-test1
  namespace: test1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        environment: dev
        release: r_09_18_v1
        tier: backend
        app: test1
    spec:
      containers:
      - name: test1
        image: gklc811/test1
        ports:
        - name: node-port
          containerPort: 5000
      nodeSelector:
        tier: backend