--- 
apiVersion: apps/v1beta1
kind: StatefulSet
metadata: 
  name: cassandra
  namespace: cassandra
spec: 
  replicas: 3
  serviceName: cassandra
  template: 
    metadata: 
      labels: 
        app: cassandra
    spec: 
      containers: 
        - 
          env: 
            - 
              name: CASSANDRA_SEEDS
              value: cassandra-0.cassandra.cassandra.svc.cluster.local
            - 
              name: MAX_HEAP_SIZE
              value: 256M
            - 
              name: HEAP_NEWSIZE
              value: 100M
            - 
              name: CASSANDRA_CLUSTER_NAME
              value: Cassandra
            - 
              name: CASSANDRA_DC
              value: DC1
            - 
              name: CASSANDRA_RACK
              value: Rack1
            - 
              name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
          image: "cassandra:3"
          imagePullPolicy: IfNotPresent
          lifecycle: 
            postStart: 
              exec: 
                command: 
                  - /bin/sh
                  - "-c"
                  - "rm -rf /var/lib/cassandra/data/*"
            preStop: 
              exec: 
                command: 
                  - /bin/sh
                  - "-c"
                  - "/usr/bin/nodetool decommission && rm -rf /var/lib/cassandra/data/*"
          name: cassandra
          ports: 
            - 
              containerPort: 7000
              name: intra-node
            - 
              containerPort: 7001
              name: tls-intra-node
            - 
              containerPort: 7199
              name: jmx
            - 
              containerPort: 9042
              name: cql
          volumeMounts: 
            - 
              mountPath: /var/lib/cassandra/data
              name: cassandra-data
      terminationGracePeriodSeconds: 900
  volumeClaimTemplates: 
    - 
      metadata: 
        annotations: 
          volume.beta.kubernetes.io/storage-class: ""
        name: cassandra-data
      spec: 
        accessModes: 
          - ReadWriteOnce
        resources: 
          requests: 
            storage: 5Gi
