--- 
apiVersion: apps/v1beta1
kind: StatefulSet
metadata: 
  name: cassandra
  namespace: cassandra
spec: 
  replicas: 3
  serviceName: cassandra
  template: 
    metadata: 
      labels: 
        app: cassandra
    spec: 
      containers: 
        - 
          env: 
            - 
              name: CASSANDRA_SEEDS
              value: cassandra-0.cassandra.cassandra.svc.cluster.local
            - 
              name: MAX_HEAP_SIZE
              value: 256M
            - 
              name: HEAP_NEWSIZE
              value: 100M
            - 
              name: CASSANDRA_CLUSTER_NAME
              value: Cassandra
            - 
              name: CASSANDRA_DC
              value: DC1
            - 
              name: CASSANDRA_RACK
              value: Rack1
            - 
              name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
          image: "registry.gokul.com:5000/gokul/cassandra"
          command: ["docker-entrypoint.sh"]
          imagePullPolicy: IfNotPresent
          name: cassandra
          ports: 
            - 
              containerPort: 7000
              name: intra-node
            - 
              containerPort: 7001
              name: tls-intra-node
            - 
              containerPort: 7199
              name: jmx
            - 
              containerPort: 9042
              name: cql
      terminationGracePeriodSeconds: 900
