- hosts: all
  gather_facts: no
  tasks:
  - name: install epel release
    yum: 
     name=epel-release 
     state=latest
  - name: upgrade all packages
    yum: 
     name='*' 
     state=latest
  - name: disable SELinux
    command: setenforce 0
  - name: disable SELinux on reboot
    selinux:
       state: disabled

- hosts: workers
  become: yes
  tasks:
  tasks:
   - name: br_netfilter
     shell: modprobe br_netfilter

   - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

- hosts: workers
  gather_facts: no
  tasks:
   - name: rebooting slaves
     reboot:

- hosts: masters
  gather_facts: no
  tasks:
   - name: rebooting master
     reboot:




